# Generated by Django 2.2.1 on 2019-05-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190527_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='company_name',
            new_name='company_id',
        ),
        migrations.AlterField(
            model_name='reviewer_metadata',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
