# Generated by Django 2.2.1 on 2019-05-27 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190528_0338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewer_metadata',
            old_name='name',
            new_name='user',
        ),
    ]
