# Generated by Django 2.2.1 on 2019-05-27 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190528_0349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='reviewer_id',
        ),
    ]
